# Generated by Django 2.0.2 on 2022-08-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASMP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='department',
            new_name='department_iitb',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='gender',
        ),
    ]
