# Generated by Django 2.0.2 on 2022-08-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASMP', '0002_auto_20220809_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='degree',
            new_name='degree_iitb',
        ),
    ]
