# Generated by Django 2.0.2 on 2022-08-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMP', '0003_auto_20220809_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asmpprofile',
            name='pref_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asmpprofile',
            name='pref_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asmpprofile',
            name='pref_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asmpprofile',
            name='pref_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asmpprofile',
            name='pref_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
