# Generated by Django 4.0.6 on 2022-08-23 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Elon Musk', max_length=50)),
                ('disc', models.TextField()),
                ('depart', models.CharField(default='CSE', max_length=50)),
                ('degree', models.CharField(default='BTech', max_length=20)),
                ('city', models.CharField(default='Washington DC', max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('coretalk', models.ManyToManyField(to='Coretalks.speaker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
