# Generated by Django 4.0.6 on 2022-08-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depart', models.TextField()),
                ('speakerType', models.TextField()),
                ('speakerDate', models.TextField()),
                ('speakerMode', models.TextField()),
                ('speakerTime', models.TextField()),
                ('speakerBio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.ManyToManyField(related_name='Speakers', to='Coretalks.speaker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
